try{
    let a = 10;
    let b = a + c;
    console.log(b)
} catch (error){
    console.log("an error occurred:", error.message);
}